import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ArrowRight, PenLine } from "lucide-react"
import { getFeaturedPost, getRecentPosts } from "@/lib/blog"
import BlogCard from "@/components/BlogCard"
import FeaturedPost from "@/components/FeaturedPost"

export default async function Home() {
  const featuredPost = await getFeaturedPost()
  const recentPosts = await getRecentPosts(3)

  return (
    <main className="min-h-screen bg-background">
      {/* Hero Section */}
      <section className="relative py-20 px-4 sm:px-6 lg:px-8 overflow-hidden">
        <div className="absolute inset-0 gradient-bg"></div>
        <div className="relative max-w-5xl mx-auto text-center">
          <h1 className="text-4xl md:text-6xl font-bold text-foreground mb-6">
            <span className="gradient-text">This Blog</span> Writes Itself
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground mb-8 max-w-2xl mx-auto">
            Cutting-edge articles generated by artificial intelligence, bringing you fresh perspectives every day.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Button asChild size="lg" className="bg-primary hover:bg-primary/90">
              <Link href="/blog">
                Explore Articles <ArrowRight className="ml-2 h-4 w-4" />
              </Link>
            </Button>
            <Button asChild variant="outline" size="lg" className="border-primary text-primary hover:bg-primary/10">
              <Link href="/about">
                Learn More <PenLine className="ml-2 h-4 w-4" />
              </Link>
            </Button>
          </div>
        </div>
      </section>

      {/* Featured Post */}
      {featuredPost && (
        <section className="py-16 px-4 sm:px-6 lg:px-8 bg-background">
          <div className="max-w-7xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-8 flex items-center">
              <PenLine className="mr-2 h-5 w-5" style={{ color: "hsl(var(--pink-accent))" }} />
              Featured Article
            </h2>
            <FeaturedPost post={featuredPost} />
          </div>
        </section>
      )}

      {/* Recent Posts */}
      {recentPosts.length > 0 && (
        <section className="py-16 px-4 sm:px-6 lg:px-8 bg-background">
          <div className="max-w-7xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-8">Recent Articles</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
              {recentPosts.map((post) => (
                <BlogCard key={post.slug} post={post} />
              ))}
            </div>
            <div className="mt-12 text-center">
              <Button asChild className="bg-primary hover:bg-primary/90">
                <Link href="/blog">View All Articles</Link>
              </Button>
            </div>
          </div>
        </section>
      )}
    </main>
  )
}
